### ISSUE TITLE
🎏 Missing Translations master tracker

### ISSUE THREAD

**Issue by nunocoracao** [nunocoracao/blowfish#1358]

**Comment by nunocoracao** [comment]
FYI @Weaxs @Lemon73-Computing @BabaRagnarok @Aphcity

**Comment by Weaxs** [comment]
🇨🇳 Chinese

- [ ] ./exampleSite/content/docs/hosting-deployment/index.zh-cn.md
- [ ]  ./exampleSite/content/guides/202310-blowfish-tutorial/index.zh-cn.md
- [ ] ./exampleSite/content/samples/placeholder-text/index.zh-cn.md

**Comment by nunocoracao** [comment]
> 🇨🇳 Chinese
> 
> * [ ]  ./exampleSite/content/docs/hosting-deployment/index.zh-cn.md
> * [ ]   ./exampleSite/content/guides/202310-blowfish-tutorial/index.zh-cn.md
> * [ ]  ./exampleSite/content/samples/placeholder-text/index.zh-cn.md

already added to the main list thanks @Weaxs

**Comment by nunocoracao** [comment]
@Weaxs @Lemon73-Computing @BabaRagnarok @Aphcity
Any update to add here?

**Comment by Weaxs** [comment]
> @Weaxs @Lemon73-Computing @BabaRagnarok @Aphcity Any update to add here?

Is it neccessary to maintain a list of docs which are pending sync if someone modifies them ?

 I saw doc for shortcode has updated, I will sync it later.

**Comment by BabaRagnarok** [comment]
Hi, sorry but I'm very busy these days and I can't keep up with all the commitments I've made. I'm carrying on with the translation as soon as I have some free time
